name: ECS Lint and Autofix

on: [push, pull_request]

name: lint
jobs:
  ecs:
    name: Easy Coding Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Easy Coding Standard Action
      uses: zingimmick/ecs-action@0.0.6